package WEB;

public enum Action {
	LOG_IN, ACTION, LOGIN_FIELD, PASS_FIELD, ERROR_CODE, ERROR_NO_USER, ERROR_NOT_MATCHES, ERROR_SETTING_SESSION, SESSION_ID, REGISTER, NAME, MAIL, PHONE, PASS, LOG_OUT, GET_ALL, EVENT, TITLE, EVENT_HOLDER, SEND
}
